<!DOCTYPE html>
<html lang="en">

<head>
    <title>Authentication</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <nav class="navbar sticky-top navbar-expand-sm bg-white shadow-sm">

        <div class="container-fluid pt-3 pb-2 d-flex align-items-center">
            <a href="/" class="text-dark navbar-brand ms-5 px-5">

                <span class=" ms-2 fw-bold fs-3">The</span><span class=" fw-normal fs-3 ">Circles</span>
            </a>

            <ul class="navbar-nav">
                <li class="nav-item px-1">
                    <a href="/login">
                        <button class="btn btn-dark rounded authButton">Sign In</button>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <main class="form-signin">
        <form method="post" action="operation" style="width: 50%;" class="mx-auto mt-5">

            <h1 class="h3 mt-3 fw-normal text-center">Please <span class='btn btn-dark'>sign in</span></h1>

            <div class="form-floating mt-3 w-75 mx-auto">
                <input type="text" class="form-control email" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email address or username</label>
            </div>
            <div class="form-floating mt-5 w-75 mx-auto">
                <input type="password" class="form-control password" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>
            <p id='error' class='text-danger'></p>
            <br>
            <a class="w-100 btn btn-lg btn-dark signin" type="submit">Sign in</a>
            <a href="/signup" class="btn text-secondary">Not a User? Sign Up</a>
        </form>
    </main>

    <!-- footer -->
    <div class="row pb-5 pt-5 mt-5">
        <p class="text-center text-muted">
            Copyright @2022 All rights reserved | The Circles
        </p>
        <a href="/" class="text-dark text-center w-25 mx-auto navbar-brand px-5">
            <i class="fa-solid fa-shop"></i>
            <span class=" ms-2 fw-bold fs-3">The</span><span class=" fw-normal fs-3">Circles</span>
        </a>
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="../public/javascript/authentication.js"></script>

</html>