<nav class="navbar sticky-top navbar-expand-sm bg-white shadow-sm">

    <div class="container-fluid pt-3 pb-2 d-flex align-items-center">
        <a href="/" class="text-dark navbar-brand ms-5 px-5">
            <span class=" ms-2 fw-bold fs-3">The</span><span class=" fw-normal fs-3 ">Circles</span>
        </a>
        <ul class="navbar-nav">
            <li class="nav-item px-1">
                <a href="/login">
                    <button class="btn btn-dark rounded authButton">Sign In</button>
                </a>
            </li>
        </ul>
    </div>
</nav>