 <section class="hero">
     <div class="container">
         <div class="row">
             <div class="col-lg-6 offset-lg-3">
                 <div class="cardbox shadow-lg bg-white">
                     <div class="cardbox-heading">
                         <div class="media m-0">
                             <div class="d-flex mr-3">
                                 <a href=""><img class="img-fluid rounded-circle" src="http://www.themashabrand.com/templates/bootsnipp/post/assets/img/users/4.jpg" alt="User"></a>
                             </div>
                             <div class="media-body">
                                 <p class="m-0 ">
                                 <h3 class='postUser'></h3>
                                 </p>
                             </div>
                         </div>
                     </div>
                     <div class="cardbox-item postImage">
                     </div>
                     <div class="cardbox-item postBody p-3">this is my post body!!</div>
                     <!--/ cardbox-item -->
                     <hr>
                     <div class="cardbox-base">
                         <ul class="float-right">
                             <li><a>
                                     <button class='btn border-0 bg-light'><i class="fa fa-comments"></i></button>
                                 </a></li>
                             <li><a><em class="mr-5 countCmnt">12</em></a></li>
                             <li><a><button class='btn border-0 bg-light share'><i class="fa fa-share-alt"></i></button></a></li>
                         </ul>
                         <ul>
                             <li><a><button class='btn border-0 bg-light btnLike'><i class="fa fa-thumbs-up colorLike" style="color:gray"></i></button></a></li>
                             <li><a><span class='likeCnt'></span></a></li>
                         </ul>
                         <hr>
                         <div class="row px-5 mb-3  w-100 ">
                             <input placeholder="Write a comment" type="text" class="mx-5 ps-5  textCmnt">
                             <input type="button" value="comment" class="btn btnCmnt">
                         </div>
                         <hr>
                         <div class="mt-5 px-4 pb-2">
                             <div class="comment">
                             </div>
                         </div>
                     </div>
                 </div>
                 <!--/ cardbox-like -->
             </div>
             <!--/ cardbox -->
         </div>
     </div>
     <!--/ row -->
     </div>
 </section>