<!DOCTYPE html>
<html lang="en">

<head>
    <title>The Circles</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="../public/css/style.css">
    <style>
        body {
            padding-left: 10%;
            padding-right: 10%;

        }
    </style>
</head>

<body>
    <?php
    include '../app/views/components/navbarHome.phtml';
    include '../app/views/components/postModal.phtml';
    echo '<div class="border">';
    
    include '../app/views/components/tab.phtml';
    include '../app/views/components/posts.phtml';
    echo '</div>';
    include '../app/views/components/footer.phtml';
    ?>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="../public/javascript/index.js"></script>

</html>